exports.Voice = require('./Ready/Voice')
exports.Data_Mic = require('./Ready/Data&Mic')
exports.Banner = require('./Ready/Banner')
exports.Presence = require('./Ready/Presence')

exports.Eval = require('./Message/Eval')
exports.New = require('./Message/New')
exports.Bug = require('./Message/Bug')
exports.Ban = require('./Message/Ban')
exports.Unban = require('./Message/Unban')
exports.Bax = require('./Message/Bax')